### ISSUE TITLE
toPhyloseq() broken in devel branch

### ISSUE THREAD

**Issue by ferreira-scm** [derele/MultiAmplicon#11]
`toPhyloseq(tMA, colnames(MA))`
Error in getSequenceTableNoChime(MA, simplify = FALSE) :
unused argument (simplify = FALSE)

When I tried the `toPhyloseq()` function without the argument "simplyfy" within `getSequenceTableNoChime()` worked just fine.

**Comment by derele** [comment]
Should have closed these when I fixed them.
