### ISSUE TITLE
toPhyloseq() broken

### ISSUE THREAD

**Issue by ferreira-scm** [derele/MultiAmplicon#6]
When running toPhyloseq(MAsample, colnames(MAsample)) after the taxonomic annotation I have the following error:

extracting 0 requested samples
Error in toPhyloseq(MAsample, colnames(MAsample)) :
empty OTU table
  rownames AA_0333 don't match sample names:
  ... (this for a bunch of other samples)

**Comment by derele** [comment]
Cool! This is actually an (helpful, I hope) error from MultiAmplicon itself!

What do you get for `colnames(MAsample)`?

What do you get for `rownames(getSampleTableNoChime(MAsample))`?

And for the `intersect()` of both?

**Comment by ferreira-scm** [comment]
`colnames(MAsample)`
NULL
`MAsample@colnames `
"AA_0441" "AA_0423" "SK_3102" "AA_0134" "SK_3063" "AA_0544" and all other samples (384)
`getSampleTableNoChime(MAsample)`
could not find function "getSampleTableNoChime"

`phyloseq::get_sample(MAsample@sequenceTableNoChime)`
Error in (function (classes, fdef, mtable)  :
unable to find an inherited method for function ‘get_sample’ for signature ‘"list"’

`lapply(MAsample@sequenceTableNoChime, rownames) `
$COX1.DINO.F_122_F.COX1.DINO.2.R_122_R                                                              
[1] "AA_0562" "AA_0239" "AA_0456" "AA_0535" "AA_0191"
....

**Comment by derele** [comment]
Hmmm... Okay! I'll have to look into this. I'm working on it on a drvrl branch for now, as I have a slightly ambitious solution...

**Comment by derele** [comment]
Most of the rownames have good intersect with the sample names, right?!

**Comment by ferreira-scm** [comment]
Yes, the sample names and colnames have a good intercept.

**Comment by derele** [comment]
This should be fixed with https://github.com/derele/MultiAmplicon/commit/1941aa7679eacc5da563c34024b1f0d9181bae12, closing it.
