### ISSUE TITLE
Not possible to use argument "dropEmpty=FALSE" in getSequenceTable()

### ISSUE THREAD

**Issue by ferreira-scm** [derele/MultiAmplicon#9]
`STF <- getSequenceTable(MAF, dropEmpty=FALSE) `

Error in getSequenceTable(MAF, dropEmpty = FALSE) :
   unused argument (dropEmpty = FALSE)

If `dropEmpty=FALSE` is not used, function works fine, but the rows from matrices don't match causing error downstream.

**Comment by ferreira-scm** [comment]
This also seems to happen in the devel version

**Comment by derele** [comment]
Fixed for me in devel in commit e65f806, please try again!

What do you mean with "downstream"? This is in the hackish code to make the chimera filtering more stringent, right?

**Comment by derele** [comment]
Please use the devel version! I'll merge into master asap.

**Comment by ferreira-scm** [comment]
It works! Thanks a lot!
